CREATE TABLE IF NOT EXISTS film (
  id integer generated by default as identity PRIMARY KEY,
  name varchar NOT NULL CHECK (name <> ''),
  description varchar(200) CHECK (LENGTH(description) > 10),
  release_date date CHECK (release_date > CAST('1895-12-28' AS DATE) AND release_date < NOW()),
  duration integer CHECK (duration > 0)
);


CREATE TABLE IF NOT EXISTS user_likes (
  id integer generated by default as identity PRIMARY KEY,
  user_id integer NOT NULL,
  film_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS film_rating (
  id integer generated by default as identity PRIMARY KEY,
  film_id integer NOT NULL unique,
  rating_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS rating (
  id integer generated by default as identity PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS film_genre (
  id integer generated by default as identity PRIMARY KEY,
  film_id integer NOT NULL,
  genre_id integer NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
  id integer generated by default as identity PRIMARY KEY,
  name varchar
);

CREATE TABLE IF NOT EXISTS users (
  id integer generated by default as identity PRIMARY KEY,
  username varchar,
  login varchar NOT NULL CHECK (login NOT LIKE '% %'),
  email varchar NOT NULL CHECK (email <> ''),
  birthday Date CHECK (birthday < NOW())
);

CREATE TABLE IF NOT EXISTS user_friends (
  id integer generated by default as identity PRIMARY KEY,
  user_id integer NOT NULL,
  friend_id integer NOT NULL
);

ALTER TABLE film_genre 
ADD FOREIGN KEY (film_id) 
REFERENCES film (id) 
ON DELETE CASCADE;

ALTER TABLE film_genre 
ADD FOREIGN KEY (genre_id) 
REFERENCES genre (id) 
ON DELETE CASCADE;

ALTER TABLE film_rating
ADD FOREIGN KEY (film_id) 
REFERENCES film (id) 
ON DELETE CASCADE;

ALTER TABLE film_rating
ADD FOREIGN KEY (rating_id) 
REFERENCES rating (id) 
ON DELETE CASCADE;

ALTER TABLE user_likes 
ADD FOREIGN KEY (film_id) 
REFERENCES film (id) 
ON DELETE CASCADE;

ALTER TABLE user_likes 
ADD FOREIGN KEY (user_id) 
REFERENCES users (id) 
ON DELETE CASCADE;

ALTER TABLE user_friends 
ADD FOREIGN KEY (user_id) 
REFERENCES users (id)
ON DELETE CASCADE;

ALTER TABLE user_friends 
ADD FOREIGN KEY (friend_id) 
REFERENCES users (id) 
ON DELETE CASCADE;